// Usuarios de prueba
export const mockUsers = [
  {
    id: '1',
    name: 'Osyual Yoel Macas',
    email: 'yoel@gmail.com',
    role: 'cliente',
    phone: '+57 300 123 4567',
    bio: 'Estudiante de Ingeniería ',
    image: 'https://i.pinimg.com/736x/af/3b/e0/af3be0fb18e0a12976162f07e585d73c.jpg',
    banner: 'https://i.pinimg.com/1200x/97/3c/7e/973c7eb2b2010905ddc01944c641e34a.jpg',
  },
  {
    id: '2',
    name: 'Luis Poma',
    email: 'Luis@gmail.com',
    role: 'estudiante',
    phone: '+57 310 234 5678',
    university: 'Universidad UIDE',
    career: 'Ingeniería de Sistemas',
    image: 'https://i.pinimg.com/736x/47/be/d6/47bed678cd8bf5b7a6466c63386cd795.jpg',
    banner: 'https://i.pinimg.com/736x/b5/5c/43/b55c43e8bb5b49e5e5e16246f226183d.jpg',
    bio: 'Desarrollador web con 3 años de experiencia. Especializado en React y Node.js',
  },
  {
    id: '3',
    name: 'Admin Principal',
    email: 'admin@uniservicios.com',
    role: 'admin',
    phone: '+57 320 345 6789',
  },
  {
    id: '4',
    name: 'Albeiro Montoya',
    email: 'Albeiro@gmail.com',
    role: 'estudiante',
    university: 'Universidad UIDE',
    career: 'Diseño Gráfico',
    bio: 'Diseñadora gráfica especializada en branding y diseño digital',
  },
  {
    id: '5',
    name: 'Juan Pérez',
    email: 'juan@ejemplo.com',
    role: 'estudiante',
    university: 'Universidad Javeriana',
    career: 'Matemáticas',
    bio: 'Tutor de matemáticas y física con 5 años de experiencia',
  },
];

// Servicios disponibles
export const mockServices = [
  {
    id: '1',
    title: 'Desarrollo de Aplicaciones Web',
    description: 'Desarrollo de aplicaciones web modernas con React, Node.js y bases de datos. Experiencia en proyectos completos desde el diseño hasta el despliegue.',
    category: 'Desarrollo Web',
    price: 15,
    providerId: '2',
    providerName: 'Carlos Ramírez',
    image: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=800',
    rating: 4.8,
    reviews: 47,
    createdAt: '2024-01-15',
  },
  {
    id: '2',
    title: 'Diseño de Logos y Branding',
    description: 'Creación de identidad visual completa para tu marca o proyecto. Incluye logo, paleta de colores, tipografía y guía de estilo.',
    category: 'Diseño Gráfico',
    price: 12,
    providerId: '4',
    providerName: 'Luis Poma',
    image: 'https://images.unsplash.com/photo-1626785774573-4b799315345d?w=800',
    rating: 5.0,
    reviews: 32,
    createdAt: '2024-01-20',
  },
  {
    id: '3',
    title: 'Tutorías de Matemáticas y Física',
    description: 'Clases personalizadas de matemáticas y física para estudiantes universitarios. Preparación para exámenes y resolución de ejercicios.',
    category: 'Tutorías',
    price: 10,
    providerId: '5',
    providerName: 'Luis Poma',
    image: 'https://images.unsplash.com/photo-1509228468518-180dd4864904?w=800',
    rating: 4.9,
    reviews: 68,
    createdAt: '2024-01-10',
  },
  {
    id: '4',
    title: 'Edición de Videos Profesional',
    description: 'Edición de videos para YouTube, redes sociales o proyectos personales. Incluye efectos, transiciones y color grading.',
    category: 'Multimedia',
    price: 18,
    providerId: '2',
    providerName: 'Jose Andres',
    image: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=800',
    rating: 4.7,
    reviews: 25,
    createdAt: '2024-01-25',
  },
  {
    id: '5',
    title: 'Asesoría en Proyectos de Grado',
    description: 'Orientación y asesoría metodológica para proyectos de grado. Ayuda en redacción, investigación y presentación.',
    category: 'Asesorías',
    price: 20,
    providerId: '5',
    providerName: 'Juan Pérez',
    image: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800',
    rating: 4.6,
    reviews: 19,
    createdAt: '2024-01-18',
  },
  {
    id: '6',
    title: 'Ilustración Digital',
    description: 'Creación de ilustraciones digitales personalizadas para libros, artículos o redes sociales. Estilo moderno y colorido.',
    category: 'Diseño Gráfico',
    price: 14,
    providerId: '4',
    providerName: 'Ana Martínez',
    image: 'https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?w=800',
    rating: 4.9,
    reviews: 41,
    createdAt: '2024-01-22',
  },
];

// Conversaciones de chat


// Categorías de servicios
export const serviceCategories = [
  'Todas',
  'Desarrollo Web',
  'Diseño Gráfico',
  'Tutorías',
  'Multimedia',
  'Asesorías',
  'Redacción',
  'Traducción',
  'Marketing',
];
